
RESULT     	= 	step2

SOURCES    	= 	gate.ml		\
			case.ml		\
			maze.ml		\
			step2.ml	\

DOC_FILES	=	gate.mli	\
			case.mli	\
			maze.mli

LIBS       	= bigarray sdl sdlloader
INCDIRS    	= +sdl

-include OCamlMakefile
